version: '0.0.1.{build}~{branch}'

os: Visual Studio 2015
platform:
  - Win32
#  - x64

configuration:
  - Release
#  - Debug

build:
  verbosity: minimal

install:
  - cmd: choco install msys2 && refreshenv
  - cmd: refreshenv && msystem.bat MSYS && pacman -Syu && bash pacman-key --init && bash pacman-key --populate msys2 && pacman --noconfirm -S bison flex

build_script:
  - cmd: |
      refreshenv 
      mkdir _build 
      cd _build 
      msystem.bat MSYS
      cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=khaotica -DCMAKE_BUILD_TYPE=Debug -DLLVM_ROOT=C:/Libraries/llvm-4.0.0 -DBOOST_ROOT=C:/Libraries/boost_1_63_0 ..
      cmake --build . --config Debug
      cmake --build . --target install
      
artifacts:
  - path: _build/khaotica
