version: "{build}"
os: Visual Studio 2015
platform:
  - Win32
#  - x64

configuration:
  - Release
#  - Debug

build:
  verbosity: minimal

install:
  - cmd: cinst msys2
  - cmd: refreshenv 
  - cmd: msystem.bat MSYS && bash pacman-key --init && bash pacman-key --populate msys2 && pacman -Syu && pacman --noconfirm -S bison flex

build_script:
  - cmd: |
      refreshenv 
      mkdir _build 
      cd _build 
      msystem.bat MSYS
      cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=khaotica -DCMAKE_BUILD_TYPE=Debug -DLLVM_ROOT=C:/Libraries/llvm-4.0.0 -DBOOST_ROOT=C:/Libraries/boost_1_63_0 ..
      cmake --build . --config Debug
      cmake --build . --target install
      
after_build:
  - git describe --tags > version.txt
  - set /p VERSION= < version.txt
  - 7z a -t7z khaotica-%VERSION%.7z ./khaotica/*
  
artifacts:
  - path: _build/khaotica-$(VERSION).7z
    name: khaotica-pkg

deploy:
  provider: GitHub
  description: '$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: U440AbFTFluGznzClLqJVmJagEJm9y1kIIZS0a6Tj9nqDb5PCI7UHuBp4apoTX1W
  artifact: khaotica-pkg
  force_update: true
  on:
    appveyor_repo_tag: true
