version: "{build}"
os: Visual Studio 2017
platform:
  - Win32
  - x64

configuration:
  - Release

build:
  verbosity: minimal

install:
  - cmd: |
        C:\msys64\msys2_shell.cmd
        pacman --noconfirm -S bison flex

build_script:
  - cmd: |
      refreshenv
      mkdir _build
      cd _build
      C:\msys64\msys2_shell.cmd
      cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=khaotica -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:/Libraries/boost_1_64_0 ..
      cmake --build . --config Release
      cmake --build . --target install

after_build:
  - git describe --tags > version.txt
  - set /p VERSION= < version.txt
  - 7z a -t7z khaotica-%VERSION%.7z ./khaotica/*

artifacts:
  - path: _build/khaotica-$(VERSION).7z
    name: khaotica-pkg

deploy:
  provider: GitHub
  description: '$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: U440AbFTFluGznzClLqJVmJagEJm9y1kIIZS0a6Tj9nqDb5PCI7UHuBp4apoTX1W
  artifact: khaotica-pkg
  force_update: true
  on:
    appveyor_repo_tag: true
