version: '0.0.1.{build}~{branch}'

os: Visual Studio 2015
platform:
  - Win32
#  - x64

configuration:
  - Release
#  - Debug

build:
  verbosity: minimal

install:
  - cmd: choco install msys2 && refreshenv && msystem.bat MSYS && pacman -Syu && pacman --noconfirm -S bison flex

before_build:
  - cmd: |
      refreshenv 
      mkdir _build 
      cd _build 
      msystem.bat MSYS
      cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=_build/khaotica -DCMAKE_BUILD_TYPE=Release -DLLVM_ROOT=C:\Libraries\llvm-4.0.0 -DBOOST_ROOT=C:\Libraries\boost_1_63_0 ..
      cmake --build . --target install
      
