language: cpp
os:
    - linux

dist: trusty

before_install:
    - sudo add-apt-repository ppa:josh-bialkowski/cmake -y
    - sudo apt-get update -qq
    - sudo apt-get install -y bison flex cmake
    - mkdir -p build/llvm
    - mkdir -p build/khaotica
    - pushd build
    - wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz
    - wget http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz
    - popd    

install:
    - pushd build
    - tar xfz boost_1_63_0.tar.gz
    - tar xfJ llvm-3.9.1.src.tar.xz
    - pushd llvm
    - cmake -DCMAKE_INSTALL_PREFIX=root -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON  ../llvm-3.9.1.src 
    - cmake --build . --target install 
    - popd
    - pushd boost_1_63_0
    - bootstrap 
    - b2 -j12 stage
    - popd

before_script:
    - ls -la build
    - ls -la build/boost_1_63_0
    - ls -la build/usr

script:
    - pushd build
    - cmake -DLLVM_ROOT=build/llvm/root -DBOOST_DIR=build/boost_1_63_0 -DCMAKE_PREFIX_INSTALL=../install ..
    - cmake --build . --target install
    - popd

after_script:
    - echo "After build script"

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file_glob: true
  file: install/*
  skip_cleanup: true
  on:
    tags: true