language: cpp
os:
    - linux

dist: trusty

cache:
  directories:
  - $HOME/deps/llvm
  - $HOME/deps/boost

notifications:
  email: false
  
before_install:
    - sudo add-apt-repository ppa:josh-bialkowski/cmake -y 
    - sudo apt-get update -qq 
    - sudo apt-get remove flex
    - sudo apt-get install -y bison cmake m4 autoconf automake

install:
    - mkdir -p build
    - |
      if [ ! -f "${HOME}/deps/llvm/cached.marker" ]; then
        mkdir -p $HOME/deps/llvm && mkdir -p build/llvm
        pushd build
            wget http://releases.llvm.org/4.0.0/llvm-4.0.0.src.tar.xz
            tar xfJ llvm-4.0.0.src.tar.xz
        
            pushd llvm
                cmake -DCMAKE_INSTALL_PREFIX=$HOME/deps/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON  -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_TOOLS=Off -DLLVM_BUILD_TOOLS=Off -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_INCLUDE_TESTS=Off ../llvm-4.0.0.src
                travis_wait 50 cmake --build . --target LLVMCodegen -- -j12
                travis_wait 50 cmake --build . -- -j12
                cmake --build . --target install
            popd
        popd
        touch ${HOME}/deps/llvm/cached.marker
      else
        echo 'Using cached LLVM libraries.'
      fi

    - |
      if [ ! -f "${HOME}/deps/boost/cached.marker" ]; then
        mkdir -p $HOME/deps/boost
        pushd build
          wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz
          tar xfz boost_1_63_0.tar.gz

          pushd boost_1_63_0
            ./bootstrap.sh
            travis_wait 50 ./b2 -j12 -d0 --prefix=$HOME/deps/boost variant=release threading=multi link=static install
          popd
        popd
        touch ${HOME}/deps/boost/cached.marker
      else
        echo 'Using cached Boost libraries.'
      fi

    - |
      pushd build
        wget https://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz
        tar xfz flex-2.6.3.tar.gz
        pushd flex-2.6.3
            ./configure && make && sudo make install
        popd
      popd

script:
    - cmake -DLLVM_ROOT=$HOME/deps/llvm -DBOOST_ROOT=$HOME/deps/boost -DCMAKE_INSTALL_PREFIX=$HOME/khaotica .
    - cmake --build . --target install -- -j12

after_success:
    - tar -zcvf $HOME/khaotica~$(git log --pretty=format:'%h' -n 1).tar.gz -C $HOME/khaotica/ .

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file_glob: true
  file: $HOME/khaotica~*.tar.gz
  skip_cleanup: true
  on:
    tags: true
