language: cpp
os:
    - linux

dist: trusty
sudo: required

cache:
  directories:
  - $HOME/deps/boost

notifications:
  email: false

before_install:
    - sudo apt-get remove -qq flex bison cmake gcc g++
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq gcc-7 m4 autoconf automake
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100

install:
    - mkdir -p build
    - |
      if [ ! -f "${HOME}/deps/boost/cached.marker" ]; then
        mkdir -p $HOME/deps/boost
        pushd build
          wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz
          tar xfz boost_1_63_0.tar.gz

          pushd boost_1_63_0
            ./bootstrap.sh
            ./b2 -j8 -d0 --prefix=$HOME/deps/boost variant=release threading=multi link=static install
          popd
        popd
        touch ${HOME}/deps/boost/cached.marker
      fi

    - |
      pushd build
        wget https://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
        tar xfz bison-3.0.4.tar.gz
        pushd bison-3.0.4
            ./configure && make && sudo make install
        popd
      popd
      
    - |
      pushd build
        wget https://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz
        tar xfz flex-2.6.3.tar.gz
        pushd flex-2.6.3
            ./configure && make && sudo make install
        popd
      popd

    - |
      pushd build
        wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.sh
        sudo sh cmake-3.9.5-Linux-x86_64.sh --skip-license --prefix=/usr/local
      popd

script:
    - cmake -DBOOST_ROOT=$HOME/deps/boost -DCMAKE_INSTALL_PREFIX=$HOME/khaotica .
    - cmake --build . --target install -- -j8

after_success:
    - tar -zcvf $HOME/khaotica-$(git describe --tags).tar.gz -C $HOME/khaotica/ .

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file_glob: true
  file: $HOME/khaotica*.tar.gz
  skip_cleanup: true
  on:
    tags: true
