/* @flavorc
 *
 * gif87a.h
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     '..\\..\\..\\fl\\gif87a.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

#ifndef _F_gif87a_h_
#define _F_gif87a_h_

// Initial size of parsable arrays: 64

// Bitstream error reporting function
void flerror(char* fmt, ...);

// Tracing functions
void trace(int pos, int size, unsigned int val, char* fmt, ...);
void trace(int pos, int size, double val, char* fmt, ...);

// Disable unreferenced local variable warning in MS Visual C++
#pragma warning(disable: 4101)
// pragma: array=256

class ColorEntry {
public:
    unsigned int r;
    unsigned int g;
    unsigned int b;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

class ColorMap {
public:
    ColorEntry *color[256];
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr, unsigned int bpp);
};
// pragma: trace

class ScreenDescriptor {
public:
    unsigned int width;
    unsigned int height;
    unsigned int M;
    unsigned int cr;
    unsigned int marker;
    unsigned int pixel;
    unsigned int background;
    ColorMap *globalColorMap;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};
// pragma: notrace

class ExtensionBlock {
public:
    unsigned int function_code;
    unsigned int byte_count;
    unsigned int data;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

class ImageData {
public:
    unsigned int code_size;
    unsigned int byte_count;
    unsigned int data;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};
// pragma: trace

class ImageDescriptor {
public:
    unsigned int left;
    unsigned int top;
    unsigned int width;
    unsigned int height;
    unsigned int M;
    unsigned int I;
    unsigned int markers;
    unsigned int pixel;
    ColorMap *localColorMap;
    ImageData *data;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

class GIF87a {
public:
    char GIFsignature[256];
    ScreenDescriptor *sd;
    unsigned int end;
    ImageDescriptor *id;
    ExtensionBlock *eb;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

#endif /* ! _F_gif87a_h_ */
