/* @flavorc
 *
 * polytest.h
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     '..\\..\\..\\fl\\polytest.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://www.ee.columbia.edu/flavor
 *
 * -- Do not edit by hand --
 *
 */

#ifndef _F_polytest_h_
#define _F_polytest_h_

// Initial size of parsable arrays: 64

// Bitstream error reporting function
void flerror(char* fmt, ...);

// Tracing functions
void trace(int pos, int size, unsigned int val, char* fmt, ...);
void trace(int pos, int size, double val, char* fmt, ...);

// Disable unreferenced local variable warning in MS Visual C++
#pragma warning(disable: 4101)
// pragma: trace

class Base {
public:
    unsigned int id;
    unsigned int marker1;
    unsigned int marker2;
    unsigned int length;
    char data[64];
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr, int _F_id_parsed = 0);
};

class Derived1 : public Base {
public:
    int d1;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr, int _F_id_parsed = 0);
};

class Derived2 : public Base {
public:
    float d2;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr, int _F_id_parsed = 0);
};

class PolyTest {
public:
    Base *b[64];
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

#endif /* ! _F_polytest_h_ */
