/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
static yyconst short int yy_accept[168] =
    {   0,
        0,    0,   73,   71,   70,   69,   50,   71,   50,   50,
       71,   50,   50,   50,   50,   50,   50,   49,   49,   50,
       50,   50,   50,   19,   50,   51,   50,   52,   27,    0,
       53,    0,    0,   35,    0,    0,    0,    3,   28,   40,
        0,   62,    0,   33,   20,   36,   21,   37,   32,   32,
       31,   44,    1,    2,   34,   43,   48,    0,    0,    0,
       49,   30,   22,   24,   26,   25,   23,   19,   41,   42,
       29,    0,    6,    0,    0,    0,    4,    0,    0,    0,
        0,    5,   54,    0,    0,   54,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   43,    0,   48,

       46,    0,   45,   47,   38,   39,    0,    0,    0,    7,
       12,    0,    0,    0,    0,    0,    0,    0,   68,   64,
       63,   66,    0,   65,   55,   56,   57,   58,   59,   60,
       61,    0,    0,   44,    0,    0,   43,   46,   11,   15,
        0,   10,   14,    0,    0,    9,   13,    0,   66,   67,
        0,   43,   46,    0,    0,    0,    0,   46,    0,   18,
        0,   16,    0,   46,    8,   17,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    6,    7,    8,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   13,   22,
       23,   24,   10,    6,   25,   26,   25,   27,   27,   25,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       13,   30,   13,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   28,   40,   41,   28,   42,   43,   44,
       45,   46,   28,   47,   28,   48,   49,   50,   28,   51,
       28,   28,   52,   53,   54,   13,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    4,    1,
        3,    3,    3,    1,    3,    3,    5,    5,    5,    5,
        3,    1,    3,    1,    5,    5,    5,    6,    6,    3,
        3,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1
    } ;

static yyconst short int yy_base[174] =
    {   0,
        0,    0,  331,  332,  332,  332,  307,  324,   44,   48,
       48,  332,  305,   46,   49,   74,   54,   82,   95,  306,
       38,  303,   51,    0,  302,  332,   45,  332,  332,  319,
      332,   51,   41,  332,   65,   43,   73,  332,  332,  332,
      314,  313,  129,  332,  332,  332,  332,  332,  310,  332,
      332,  124,  332,  332,  332,  138,  151,   87,  109,    0,
      166,  332,  297,  332,  332,  332,  296,    0,  332,  332,
      332,   89,  332,  120,  266,  104,  332,  271,  281,  154,
      282,  332,  332,  305,  304,  303,  173,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  187,  191,  202,  214,

       89,  206,  218,    0,  332,  332,  250,  249,  259,  332,
      332,  234,  208,  214,  215,  194,  188,  191,  332,  332,
      332,  332,  230,  332,  332,  332,  332,  332,  332,  332,
      332,  208,  225,  235,  244,  248,  252,  119,  332,  332,
      169,  332,  332,  153,  149,  332,  332,  121,  332,  332,
      256,  260,  132,  108,   92,   59,   48,  179,   27,  332,
       27,  332,  135,  195,  332,  332,  332,  278,  284,  286,
      292,   57,  295
    } ;

static yyconst short int yy_def[174] =
    {   0,
      167,    1,  167,  167,  167,  167,  167,  168,  167,  167,
      169,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  170,  167,  167,  167,  167,  167,  168,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  171,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  172,
      167,  167,  167,  167,  167,  167,  167,  170,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  173,  167,  167,  167,  167,

      167,  167,  167,  172,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  173,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,    0,  167,  167,  167,
      167,  167,  167
    } ;

static yyconst short int yy_nxt[387] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   12,   15,   16,   17,   18,   19,   19,   19,
       20,   21,   22,   23,   24,   24,   24,   24,   24,    4,
       25,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   26,   27,   28,   32,   39,   42,   45,   33,   63,
       64,  104,   47,  166,   53,   72,   34,   70,   46,   54,
       40,   48,   49,   66,   67,   74,   55,   43,  165,   76,
      162,   75,   35,   36,   50,   78,   79,   80,   51,   37,
       52,   52,   52,   52,  161,   38,   56,   71,   57,   57,

       57,   57,   73,  101,  101,  138,  138,   58,   59,   56,
       60,   61,   61,   61,   61,   58,   77,   59,   59,   81,
      102,   59,  102,  107,   82,  103,  103,  103,  103,  108,
       59,   59,   60,   85,  109,  153,  153,   86,  112,  160,
       52,   52,   52,   52,  113,   87,   87,   87,  158,  158,
       97,  101,  101,  159,   98,   98,   98,   98,   88,   97,
       97,   89,   90,  157,   99,   56,   91,  100,  100,  100,
      100,  110,   92,   99,   99,   93,   94,   59,   95,   96,
       56,  122,   61,   61,   61,   61,   59,   59,  116,  123,
      123,  123,   59,  163,  117,  164,  164,  156,  133,  155,

      133,   59,   59,  134,  134,  134,  134,   98,   98,   98,
       98,  164,  164,  136,  154,  136,  150,  135,  137,  137,
      137,  137,  103,  103,  103,  103,  135,  135,   56,  148,
      100,  100,  100,  100,  103,  103,  103,  103,  149,  147,
       59,  134,  134,  134,  134,  146,  123,  123,  123,   59,
       59,  134,  134,  134,  134,  151,  145,  151,  144,  143,
      152,  152,  152,  152,  137,  137,  137,  137,  137,  137,
      137,  137,  152,  152,  152,  152,  152,  152,  152,  152,
       30,   30,   30,   30,   41,  142,   41,   41,   41,   41,
       68,   68,   84,  141,   84,   84,   84,   84,  132,  132,

      140,  139,  119,  131,  130,  129,  128,  127,  126,  125,
      124,  121,  120,  119,  118,  115,  114,  111,  106,  105,
       50,   83,   83,   31,   69,   65,   62,   44,   31,   29,
      167,    3,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167
    } ;

static yyconst short int yy_chk[387] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   14,    9,   21,
       21,  172,   15,  161,   17,   32,    9,   27,   14,   17,
       10,   15,   15,   23,   23,   33,   17,   11,  159,   35,
      157,   33,    9,    9,   16,   36,   36,   37,   16,    9,
       16,   16,   16,   16,  156,    9,   18,   27,   18,   18,

       18,   18,   32,   58,   58,  101,  101,   18,   18,   19,
       18,   19,   19,   19,   19,   18,   35,   18,   18,   37,
       59,   19,   59,   72,   37,   59,   59,   59,   59,   72,
       19,   19,   18,   43,   74,  138,  138,   43,   76,  155,
       52,   52,   52,   52,   76,   43,   43,   43,  153,  153,
       52,  163,  163,  154,   56,   56,   56,   56,   43,   52,
       52,   43,   43,  148,   56,   57,   43,   57,   57,   57,
       57,   74,   43,   56,   56,   43,   43,   57,   43,   43,
       61,   87,   61,   61,   61,   61,   57,   57,   80,   87,
       87,   87,   61,  158,   80,  158,  158,  145,   97,  144,

       97,   61,   61,   97,   97,   97,   97,   98,   98,   98,
       98,  164,  164,   99,  141,   99,  132,   98,   99,   99,
       99,   99,  102,  102,  102,  102,   98,   98,  100,  118,
      100,  100,  100,  100,  103,  103,  103,  103,  123,  117,
      100,  133,  133,  133,  133,  116,  123,  123,  123,  100,
      100,  134,  134,  134,  134,  135,  115,  135,  114,  113,
      135,  135,  135,  135,  136,  136,  136,  136,  137,  137,
      137,  137,  151,  151,  151,  151,  152,  152,  152,  152,
      168,  168,  168,  168,  169,  112,  169,  169,  169,  169,
      170,  170,  171,  109,  171,  171,  171,  171,  173,  173,

      108,  107,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   86,   85,   84,   81,   79,   78,   75,   67,   63,
       49,   42,   41,   30,   25,   22,   20,   13,    8,    7,
        3,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"

/*
 * Copyright (c) 1997-2004 Alexandros Eleftheriadis, Danny Hong and 
 * Yuntai Kyong.
 *
 * This file is part of Flavor, developed at Columbia University
 * (http://flavor.sourceforge.net).
 *
 * Flavor is free software; you can redistribute it and/or modify
 * it under the terms of the Flavor Artistic License as described in
 * the file COPYING.txt. 
 *
 */

/*
 * Authors:
 * Alexandros Eleftheriadis <eleft@ee.columbia.edu>
 * Danny Hong <danny@ee.columbia.edu>
 * Yuntai Kyong <yuntaikyong@ieee.org>
 *
 */

/*
 * Lexical analyzer for the Flavor translator
 */

#include <stdio.h>
#include <stdarg.h>
#include <string.h>

#include "port.h"
#include "globals.h"
#include "symbol.h"
#include "ptree.h"
#include "util.h"
#include "error.h"
#include "compile.h"

#include "parser.tab.h"

/* symbol lookup */
static int getsymbol(void);

/* error reporting */
void yyerror(char *fmt, ...);

/* comment processing */
void yycomment(char *end);

/* transparent user-code processing */
verbatim_t *yyverbatim(char *end);

/* sometimes yywrap is defined as a macro */
#undef yywrap

/* disable 'unreferenced label' warning from Visual C++ */
#pragma warning(disable : 4102)

/* Set when processing pragma statements.
 * Suppresses regular symbol lookup -- see getsymbol() below.
 */
static int pragma_active = 0;

/* parser entry point */
int yyparse();

#line 570 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 79 "lexer.l"


#line 724 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 168 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 332 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 81 "lexer.l"
yycomment("*/");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "lexer.l"
yycomment("\n");
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 84 "lexer.l"
yylval.vp=yyverbatim("%}"); return VERBATIM;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "lexer.l"
yylval.vp=yyverbatim("%g}"); return VERBATIM_GET;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "lexer.l"
yylval.vp=yyverbatim("%p}"); return VERBATIM_PUT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "lexer.l"
yylval.vp=yyverbatim("%*}"); return VERBATIM_BOTH;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "lexer.l"
yylval.vp=yyverbatim("%.c}"); return VERBATIM_C;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "lexer.l"
yylval.vp=yyverbatim("%.c.cpp}"); return VERBATIM_C_CPP;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "lexer.l"
yylval.vp=yyverbatim("%p.c}"); return VERBATIM_PUT_C;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "lexer.l"
yylval.vp=yyverbatim("%g.c}"); return VERBATIM_GET_C;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "lexer.l"
yylval.vp=yyverbatim("%*.c}"); return VERBATIM_BOTH_C;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "lexer.l"
yylval.vp=yyverbatim("%.j}"); return VERBATIM_J;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "lexer.l"
yylval.vp=yyverbatim("%p.j}"); return VERBATIM_PUT_J;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "lexer.l"
yylval.vp=yyverbatim("%g.j}"); return VERBATIM_GET_J;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "lexer.l"
yylval.vp=yyverbatim("%*.j}"); return VERBATIM_BOTH_J;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 110 "lexer.l"
pragma_active=1; return yylval.ival=PRAGMA;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "lexer.l"
return yylval.ival=INCLUDE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "lexer.l"
return yylval.ival=IMPORT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "lexer.l"
{
    int c = getsymbol();
    if (c) return c;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 121 "lexer.l"
return yylval.ival=INC;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 122 "lexer.l"
return yylval.ival=DEC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 123 "lexer.l"
return yylval.ival=LS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "lexer.l"
return yylval.ival=RS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "lexer.l"
return yylval.ival=LE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "lexer.l"
return yylval.ival=GE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "lexer.l"
return yylval.ival=EQ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "lexer.l"
return yylval.ival=NE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "lexer.l"
return yylval.ival=AND;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "lexer.l"
return yylval.ival=OR;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "lexer.l"
return yylval.ival=CLCL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 132 "lexer.l"
return yylval.ival=RANGE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "lexer.l"
{
    yyerror("C++ operator '%s' not supported in Flavor", yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 138 "lexer.l"
return yylval.ival=MUL_ASSIGN;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 139 "lexer.l"
return yylval.ival=DIV_ASSIGN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 140 "lexer.l"
return yylval.ival=MOD_ASSIGN;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "lexer.l"
return yylval.ival=ADD_ASSIGN;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "lexer.l"
return yylval.ival=SUB_ASSIGN;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "lexer.l"
return yylval.ival=LS_ASSIGN;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 144 "lexer.l"
return yylval.ival=RS_ASSIGN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 145 "lexer.l"
return yylval.ival=AND_ASSIGN;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 146 "lexer.l"
return yylval.ival=XOR_ASSIGN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 147 "lexer.l"
return yylval.ival=OR_ASSIGN;
	YY_BREAK
case 43:
#line 150 "lexer.l"
case 44:
#line 151 "lexer.l"
case 45:
YY_RULE_SETUP
#line 151 "lexer.l"
{
    /* double number */
    char *stop;
    yylval.dval = strtod(yytext, &stop);
    if (strlen(stop) > 0) yyerror("Incorrect double number");
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "lexer.l"
{
    /* bitstring */ 
    int i;
    unsigned int shift;
    
    yylval.bit = (bit_t *)getmem(sizeof(bit_t));

    /* compute value */
    yylval.bit->len = 0;
    yylval.bit->val = 0;
    shift = 1;
    for (i=yyleng-1; i>=2; i--) {
        if (yytext[i] == '.') continue;
        if (yytext[i] == '1') yylval.bit->val|=shift;
        shift = shift<<1;
        /* we only accept up to 32 bits */
        if (yylval.bit->len == 32) {
            yyerror("Bitstring value longer than 32 bits");
            return BIT_LITERAL;
        } 
        else yylval.bit->len++;
    }
    return BIT_LITERAL;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 184 "lexer.l"
{
    /* hexadecimal - treated as bitstring */

    yylval.bit = (bit_t *)getmem(sizeof(bit_t));

    /* we only accept up to 32 bits */
    if (yyleng-2 > 8) {
        yyerror("Hexadecimal value longer than 32 bits");
        yylval.bit->len = 32;
        yylval.bit->val = strtol(yytext+yyleng-8, (char **)NULL, 16);
    }
    else {
        /* every hex digit is taken as 4 bits */
        yylval.bit->len = (yyleng-2)*4;
        yylval.bit->val = strtoul(yytext+2, (char **)NULL, 16);
    }
    return BIT_LITERAL;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 203 "lexer.l"
{
    /* octal number - treated as bitstring */

    yylval.bit = (bit_t *)getmem(sizeof(bit_t));

    /* we only accept up to 32 bits */
    if (yyleng-2 > 10) {
        yyerror("Octal value longer than 32 bits");
        yylval.bit->len = 30;
        yylval.bit->val = strtol(yytext+yyleng-10, (char **)NULL, 8);
    }
    else {
        /* every octal digit is taken as 3 bits */
        yylval.bit->len = (yyleng-2)*3;
        yylval.bit->val = strtol(yytext+1, (char **)NULL, 8);
    }
    return BIT_LITERAL;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "lexer.l"
{
    /* int number */
    char *stop;

    yylval.ival = strtol(yytext, &stop, 10);
    if (strlen(stop) > 0) yyerror("Incorrect integer number");
    return INT_LITERAL;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 231 "lexer.l"
return yylval.ival = *yytext;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 233 "lexer.l"
s_newcontext(0); return yylval.ival = *yytext;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 235 "lexer.l"
s_remcontext(); return yylval.ival = *yytext;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 237 "lexer.l"
{
    /* copy, trimming initial and final '"' */
    yylval.string = strdup(yytext+1);
    if (yylval.string == NULL) fatal("Could not allocate memory (%d bytes)", strlen(yytext)+1);
    yylval.string[strlen(yylval.string)-1] = '\0';
    return STRING_LITERAL;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "lexer.l"
yylval.ival=yytext[1]; return INT_LITERAL;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "lexer.l"
yylval.ival='\a'; return INT_LITERAL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "lexer.l"
yylval.ival='\b'; return INT_LITERAL;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "lexer.l"
yylval.ival='\f'; return INT_LITERAL;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "lexer.l"
yylval.ival='\n'; return INT_LITERAL;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "lexer.l"
yylval.ival='\r'; return INT_LITERAL;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "lexer.l"
yylval.ival='\t'; return INT_LITERAL;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "lexer.l"
yylval.ival='\v'; return INT_LITERAL;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 253 "lexer.l"
yylval.ival='?'; return INT_LITERAL;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "lexer.l"
yylval.ival='\''; return INT_LITERAL;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "lexer.l"
yylval.ival='\"'; return INT_LITERAL;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 256 "lexer.l"
yylval.ival='\\'; return INT_LITERAL;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 258 "lexer.l"
{
    /* ascii code in octal */
    char *stop;

    yylval.ival = strtol(yytext+2, &stop, 8);
    if (strlen(stop) != 1 || yylval.ival > 255)
        yyerror("Incorrect ASCII code in char constant: %d", yylval.ival);
    return INT_LITERAL;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 268 "lexer.l"
{
    /* ascii code in hex */
    char *stop;

    yylval.ival = strtol(yytext+3, &stop, 16);
    if (strlen(stop) != 1 || yylval.ival > 255)
        yyerror("Incorrect ASCII code in char constant: %d", yylval.ival);
    return INT_LITERAL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 278 "lexer.l"
yylval.ival=yytext[2]; return INT_LITERAL;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 280 "lexer.l"
{ lineno++; pragma_active = 0; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 282 "lexer.l"
;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return yytext[0]; };
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 286 "lexer.l"
ECHO;
	YY_BREAK
#line 1258 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 168 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 168 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 167);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 286 "lexer.l"


/* lookup symbol */
static int getsymbol()
{
    symbol_t *sp;

    if (pragma_active) {
        sp = s_pragma_lookup(yytext);
        if (sp != NULL) {
            /* all pragma symbols are internal and not exported */
            yylval.ival = sp->ident;
            return sp->ident;
    	}
    	/* pragma lookup failed; disable and do a regular lookup */
    	pragma_active = 0;
    }
    sp = s_lookupadd(yytext, VARIABLE);

    if (sp->ident == 0) {
        yyerror("Reserved keyword '%s' cannot be used", yytext);
        return 0;
    }
    if (sp->internal && !sp->exported){
        yylval.ival = sp->ident;
    }
    else {
        yylval.sp = sp;
    }

    return sp->ident;
}

/* varargs version */
void yyerror(char *fmt, ...)
{
    va_list ap;
    char buf[256];

    /* keep track of how many errors we found */
    nerrors++;

    va_start(ap, fmt);
    vsprintf(buf, fmt, ap);
    va_end(ap);

    if (!msvc) {
        if (feof(yyin)) {
            /* in MKS Lex, lineno and yytext are wrong after EOF */
            fprintf(stderr, "%s:%d: %s\n", filename, lineno-1, buf);
    	}
        else {
            /* print next token if just 'Syntax error' */
            if (strcmp(buf, "Syntax error")==0)
    	        fprintf(stderr, "%s:%d: %s: '%s'\n", filename, lineno, buf, yytext);
            else
    	        fprintf(stderr, "%s:%d: %s\n", filename, lineno, buf);
        }
    }
    else {
        if (feof(yyin)) {
            /* in MKS Lex, lineno and yytext are wrong after EOF */
            fprintf(stderr, "%s(%d) : error: %s\n", filename, lineno-1, buf);
        }
        else {
	    /* print next token if just 'Syntax error' */
	    if (strcmp(buf, "Syntax error")==0)
	        fprintf(stderr, "%s(%d) : error: %s: '%s'\n", filename, lineno, buf, yytext);
	    else
	        fprintf(stderr, "%s(%d) : error: %s\n", filename, lineno, buf);
        }
    }
    return;
}

/* skip input until end of comment */
void yycomment(char *end)
{
    int c, startline;
    char *cp;

    startline = lineno;
    for (cp=end; *cp!='\0'; ) {
        c = input();
        if (c == EOF) {
            yyerror("End of file in comment started at line %d", startline);
            exit(1);
        }
        if (c == '\n') lineno++;
        if (c != *cp++) {
            cp = end;
            if (c == *cp) cp++;
        }
    }
}

/*
 * Transparently pass user to code to the output file.
 * Returns verbatim code.
 */
verbatim_t *yyverbatim(char *end)
{
    int c;
    char *cp, *sp;
    verbatim_t *vp;

    vp = (verbatim_t *)getmem(sizeof(verbatim_t));

    /* we need to hold off so that we don't print the 'end' characters */

    vp->lineno = lineno;
    vp->str = NULL;
    for (cp=end; *cp!='\0'; ) {
        c = input();
        if (c == EOF) {
            yyerror("End of file in verbatim section started at line %d", vp->lineno);
            exit(1);
        }
        if (c == '\n') lineno++;
        if (c != *cp++) {
            /* no match, output and restart */
            sp = end;
            while (sp < cp-1) vp->str = buildstr(vp->str, *sp++);
            cp = end;
            /* see if at least the first 'end' char matches */
            if (c == *cp) cp++;
            else vp->str = buildstr(vp->str, c);
        }
    }
    return vp;
}

/* state stack (reversed) for include file processing */
typedef struct _state_t {
    char filename[MAX_LEN];
    int lineno;
    FILE *yyin;
    int max_array_size;
    int null_strings;
    int import;     /* set to 1 if import, 0 if include */
    struct _state_t *next;
} state_t;

static state_t *state_top=NULL;

/* push; returns 0 if file with same base name has already been included */
static int state_push(char *newfname, FILE *newfp, int import)
{
    state_t *sp, *tp;

    /* sanity check: can't include ourselves */
    if (strcmp(basename(newfname), basename(filename)) == 0) return 0;

    sp = (state_t *)getmem(sizeof(state_t));

    /* add to stack */
    if (state_top == NULL) state_top = sp;
    else {
        tp = state_top;
        while (tp != NULL) {
            /* detect loops */
#if defined(WIN32) || defined(_WIN32_)
            if (stricmp(basename(newfname), basename(tp->filename))==0) {
#else
            if (strcmp(basename(newfname), basename(tp->filename))==0) {
#endif
                free(sp);
                return 0;
            }
            if (tp->next == NULL) break;
            tp = tp->next;
        }
        tp->next = sp;
    }
    strcpy(sp->filename, filename);
    strcpy(filename, newfname);
    sp->import = import;
    sp->max_array_size = max_array_size;
    sp->null_strings = null_strings;
    sp->lineno = lineno;
    sp->yyin = yyin;
    yyin = newfp;
    lineno = 1;
    sp->next = NULL;

    return 1;
}

static void state_pop(void)
{
    state_t *sp, *prevsp;

    if (state_top == NULL) fatal("Internal error L%d: State stack is empty", __LINE__);
    
    /* find entry at the bottom of stack */
    prevsp = NULL;
    sp = state_top;
    while (sp->next != NULL) {
        if (prevsp == NULL) prevsp = sp;
        else prevsp = prevsp->next;
        sp = sp->next;
    }
    /* restore state */
    strcpy(filename, sp->filename);
    lineno = sp->lineno;
    yyin = sp->yyin;
    /* pop max_array_size and null_strings *only* if we are including */
    if (including()) {
        max_array_size = sp->max_array_size;
        null_strings = sp->null_strings;
    }

    /* unlink entry */
    if (prevsp == NULL) state_top = NULL;
    else prevsp->next = NULL;

    free(sp);
}

/*
 * Are we currently processing an include file? 
 * An import is only treated as such if all previous includes where imports themselves.
 */
int including(void)
{
    state_t *sp;
   
    sp = state_top;
    while (sp != NULL) {
        if (!sp->import) return 1;
        sp = sp->next;
    }
    return 0;
}

/* file processing continuation (0 means there is more input) */
int yywrap(void) 
{
    if (state_top != NULL) {
        state_pop();
        return 0;
    }
    return 1;
}

/* process include/import file (returns 0 if a loop would occur) */
int include(char *file, int import)
{
    char path[MAX_LEN]; /* full path to included file */
    FILE *fp;

    /* input filename must end with .fl */
    if (strcmp(&file[ strlen(file) >= 3 ? strlen(file)-3 : 0 ], ".fl"))
        fatal("Included file does hot have '.fl' suffix: %s", file);

    if (!isabsolute(file)) {
        strcpy(path, dirname(filename));
        strcat(path, file);
    }
    else strcpy(path, file);

    /* open input file  */
    if ((fp = fopen(path, "r")) == NULL) fatal("Cannot open included file: %s", path);

    /* switch state */
    if (!state_push(path, fp, import)) {
        fclose(fp);
        return 0;
    }

    /* let the parser continue */
    return 1;
}

