/* @flavorc
 *
 * basic.h
 * 
 * This file was automatically generated by flavorc
 * from the source file:
 *     '..\\..\\..\\fl\\basic.fl'
 *
 * For information on flavorc, visit the Flavor Web site at:
 *     http://flavor.sourceforge.net
 *
 * -- Do not edit by hand --
 *
 */

#ifndef _F_basic_h_
#define _F_basic_h_

// initial size of parsable arrays: 64

// bitstream error reporting function
void flerror(char* fmt, ...);

// disable unreferenced local variable warning in MS Visual C++
#pragma warning(disable: 4101)

class Basic {
public:
    char abc[64];
    unsigned int num1;
    unsigned int next_parse_len;
    int num2;
    unsigned int num3;
    public: virtual int putxml(IBitstream &_F_bs, short int bAttr);
};

#endif /* ! _F_basic_h_ */
